Repository jalantechnologies/flask-react-template, pull requests merged in 2025-02, with the labels that each got.

#116 update node version to 22.13.1
  .nvmrc
  Dockerfile
  Pipfile.lock
  README.md
  package-lock.json
  package.json
Labels: enhancement

#127 style: reformat files
  src/apps/frontend/contexts/account.provider.tsx
  src/apps/frontend/services/account.service.ts
  src/apps/frontend/services/auth.service.ts
  src/apps/frontend/types/auth.ts
Labels: chore

#91 Chore: Refactor to discontinue pydantic
  src/apps/backend/modules/access_token/rest_api/access_token_view.py
  src/apps/backend/modules/account/errors.py
  src/apps/backend/modules/account/internal/account_reader.py
  src/apps/backend/modules/account/internal/account_util.py
  src/apps/backend/modules/account/internal/account_writer.py
  src/apps/backend/modules/account/internal/store/account_model.py
  src/apps/backend/modules/account/internal/store/account_repository.py
  src/apps/backend/modules/account/rest_api/account_view.py
  src/apps/backend/modules/account/types.py
  src/apps/backend/modules/common/base_model.py
  src/apps/backend/modules/otp/internal/otp_util.py
  src/apps/backend/modules/otp/internal/otp_writer.py
  src/apps/backend/modules/otp/internal/store/otp_model.py
  src/apps/backend/modules/otp/internal/store/otp_repository.py
  src/apps/backend/modules/password_reset_token/internal/password_reset_token_util.py
  src/apps/backend/modules/password_reset_token/internal/password_reset_token_writer.py
  src/apps/backend/modules/password_reset_token/internal/store/password_reset_token_model.py
  src/apps/backend/modules/password_reset_token/internal/store/password_reset_token_repository.py
  src/apps/backend/modules/password_reset_token/password_reset_token_service.py
  tests/modules/access_token/test_access_token_api.py
  tests/modules/access_token/test_access_token_service.py
  tests/modules/account/test_account_api.py
  tests/modules/account/test_account_service.py
  tests/modules/password_reset_token/test_password_reset_token_api.py
Labels: chore

#128 fix: Add test checks
  Makefile
Labels: bug
