Repository jalantechnologies/flask-react-template, pull requests merged in 2025-03, with the labels that each got.

#87 Chore: Refactor Config Module
  README.md
  config/custom-environment-variables.yml
  config/default.yml
  config/development.yml
  config/docker-dev.yml
  config/docker-test.yml
  config/preview.yml
  config/production.yml
  config/testing.yml
  src/apps/backend/modules/access_token/access_token_service.py
  src/apps/backend/modules/application/repository.py
  src/apps/backend/modules/common/dict_util.py
  src/apps/backend/modules/communication/internals/sendgrid_service.py
  src/apps/backend/modules/communication/internals/twilio_service.py
  src/apps/backend/modules/communication/sms_service.py
  src/apps/backend/modules/config/config_manager.py
  src/apps/backend/modules/config/config_service.py
  src/apps/backend/modules/config/internals/__init__.py
  src/apps/backend/modules/config/internals/config_files/app_env_config_file.py
  src/apps/backend/modules/config/internals/config_files/custom_env_config_file.py
  src/apps/backend/modules/config/internals/config_files/default_config_file.py
  src/apps/backend/modules/config/internals/config_manager.py
  src/apps/backend/modules/config/internals/config_utils.py
  src/apps/backend/modules/config/internals/types.py
  src/apps/backend/modules/config/types.py
  src/apps/backend/modules/error/custom_errors.py
  src/apps/backend/modules/logger/internal/console_logger.py
  src/apps/backend/modules/logger/internal/datadog_handler.py
  src/apps/backend/modules/logger/internal/datadog_handler_level.py
  src/apps/backend/modules/logger/internal/loggers.py
  src/apps/backend/modules/otp/internal/otp_util.py
  src/apps/backend/modules/password_reset_token/internal/password_reset_token_util.py
  src/apps/backend/modules/password_reset_token/password_reset_token_service.py
  src/apps/backend/server.py
  src/apps/backend/settings/__init__.py
  src/apps/backend/settings/default.py
  src/apps/backend/settings/development.py
  src/apps/backend/settings/os_envs.py
  src/apps/backend/settings/preview.py
  src/apps/backend/settings/production.py
  src/apps/backend/settings/testing.py
  src/apps/backend/settings/types.py
  tests/modules/account/base_test_account.py
  tests/modules/account/test_account_api.py
  tests/modules/common/test_dict_util.py
  tests/modules/config/base_test_config.py
  tests/modules/config/test_config.py
  tests/modules/password_reset_token/base_test_password_reset_token.py
Labels: chore

#130 feat: add support for queuing workers via temporal
  Makefile
  Pipfile
  Pipfile.lock
  README.md
  config/development.yml
  config/docker-dev.yml
  config/docker-test.yml
  config/testing.yml
  docker-compose.dev.yml
  docker-compose.test.yml
  package.json
  src/apps/backend/modules/application/__init__.py
  src/apps/backend/modules/application/application_service.py
  src/apps/backend/modules/application/errors.py
  src/apps/backend/modules/application/internal/__init__.py
  src/apps/backend/modules/application/internal/worker_manager.py
  src/apps/backend/modules/application/types.py
  src/apps/backend/modules/application/workers/health_check_worker.py
  src/apps/backend/server.py
  src/apps/backend/temporal_config.py
  src/apps/backend/temporal_server.py
  temporal-sql.yaml
  tests/modules/application/__init__.py
  tests/modules/application/base_test_application.py
  tests/modules/application/test_application_service.py
Labels: enhancement

#137 fix: resolve deployment issue due to temporal connection failing
  config/custom-environment-variables.yml
  src/apps/backend/modules/application/errors.py
  src/apps/backend/server.py
Labels: bug

#139 feat: Implement Config-Based Authentication Mechanism in Login/Signup
  config/default.yml
  src/apps/frontend/constants/index.ts
  src/apps/frontend/constants/routes.ts
  src/apps/frontend/pages/authentication/otp/index.tsx
  src/apps/frontend/pages/authentication/otp/otp-form.tsx
  src/apps/frontend/pages/authentication/phone-login/phone-login-form.hook.ts
  src/apps/frontend/pages/authentication/phone-login/phone-login-form.tsx
  src/apps/frontend/pages/authentication/signup/signup-form.tsx
  src/apps/frontend/pages/login/login-form.tsx
  src/apps/frontend/routes/auth-route.tsx
  src/apps/frontend/types/form.ts
Labels: chore

#141 refactor: phonelogin and otp routes
  src/apps/frontend/constants/routes.ts
  src/apps/frontend/pages/authentication/otp/index.tsx
  src/apps/frontend/pages/authentication/otp/otp-form.tsx
  src/apps/frontend/pages/authentication/phone-login/phone-login-form.hook.ts
  src/apps/frontend/pages/authentication/phone-login/phone-login-form.tsx
  src/apps/frontend/pages/index.ts
  src/apps/frontend/pages/login/login-form.tsx
  src/apps/frontend/routes/auth-route.tsx
  src/apps/frontend/routes/public.tsx
Labels: chore

#148 Refactor: Add absolute paths to frontend
  src/apps/frontend/app.component.tsx
  src/apps/frontend/components/button/index.tsx
  src/apps/frontend/components/flex/flex-item.component.tsx
  src/apps/frontend/components/flex/flex.component.tsx
  src/apps/frontend/components/form-control/index.tsx
  src/apps/frontend/components/header/index.tsx
  src/apps/frontend/components/header/user-menu-dropdown.component.tsx
  src/apps/frontend/components/header/user-profile-snippet.component.tsx
  src/apps/frontend/components/index.ts
  src/apps/frontend/components/input/index.tsx
  src/apps/frontend/components/input/password-input.tsx
  src/apps/frontend/components/layouts/custom-layout.component.tsx
  src/apps/frontend/components/otp/index.tsx
  src/apps/frontend/components/otp/otp-input.tsx
  src/apps/frontend/components/sidebar/index.tsx
  src/apps/frontend/contexts/account.provider.tsx
  src/apps/frontend/contexts/async.hook.ts
  src/apps/frontend/contexts/auth.provider.tsx
  src/apps/frontend/contexts/index.ts
  src/apps/frontend/contexts/reset-password.provider.tsx
  src/apps/frontend/helpers/index.ts
  src/apps/frontend/index.tsx
  src/apps/frontend/pages/app-layout/app-layout.tsx
  src/apps/frontend/pages/authentication/authentication-form-layout.tsx
  src/apps/frontend/pages/authentication/forgot-password/forgot-password-form.hook.ts
  src/apps/frontend/pages/authentication/forgot-password/forgot-password-form.tsx
  src/apps/frontend/pages/authentication/forgot-password/forgot-password-resend-email.tsx
  src/apps/frontend/pages/authentication/forgot-password/index.tsx
  src/apps/frontend/pages/authentication/otp/index.tsx
  src/apps/frontend/pages/authentication/otp/otp-form-hook.ts
  src/apps/frontend/pages/authentication/otp/otp-form.tsx
  src/apps/frontend/pages/authentication/phone-login/index.tsx
  src/apps/frontend/pages/authentication/phone-login/phone-login-form.hook.ts
  src/apps/frontend/pages/authentication/phone-login/phone-login-form.tsx
  src/apps/frontend/pages/authentication/reset-password/index.tsx
  src/apps/frontend/pages/authentication/reset-password/reset-password-form.hook.ts
  src/apps/frontend/pages/authentication/reset-password/reset-password-form.tsx
  src/apps/frontend/pages/authentication/signup/index.tsx
  src/apps/frontend/pages/authentication/signup/signup-form.hook.ts
  src/apps/frontend/pages/authentication/signup/signup-form.tsx
  src/apps/frontend/pages/index.ts
  src/apps/frontend/pages/login/index.tsx
  src/apps/frontend/pages/login/login-form.hook.ts
  src/apps/frontend/pages/login/login-form.tsx
  src/apps/frontend/routes/index.tsx
  src/apps/frontend/routes/protected.tsx
  src/apps/frontend/routes/public.tsx
  src/apps/frontend/services/account.service.ts
  src/apps/frontend/services/api.service.ts
  src/apps/frontend/services/auth.service.ts
  src/apps/frontend/services/index.ts
  src/apps/frontend/services/reset-password.service.ts
  src/apps/frontend/types/account.ts
  src/apps/frontend/types/async-operation.ts
  src/apps/frontend/types/auth.ts
  src/apps/frontend/types/index.ts
  src/apps/frontend/types/service-response.ts
  src/apps/frontend/utils/storage-util.ts
  src/apps/frontend/webpack.base.js
  tsconfig.json
Labels: chore
