Repository jalantechnologies/flask-react-template, pull requests merged in 2025-07, with the labels that each got.

#245 chore: update Dockerfile to install jq
  Dockerfile
Labels: bug, chore

#258 feat: add user notification preferences with configurable email, SMS, and push notification
  src/apps/backend/modules/account/account_service.py
  src/apps/backend/modules/account/rest_api/account_router.py
  src/apps/backend/modules/account/rest_api/account_view.py
  src/apps/backend/modules/authentication/authentication_service.py
  src/apps/backend/modules/notification/email_service.py
  src/apps/backend/modules/notification/errors.py
  src/apps/backend/modules/notification/internals/account_notification_preferences_reader.py
  src/apps/backend/modules/notification/internals/account_notification_preferences_util.py
  src/apps/backend/modules/notification/internals/account_notification_preferences_writer.py
  src/apps/backend/modules/notification/internals/store/__init__.py
  src/apps/backend/modules/notification/internals/store/account_notification_preferences_model.py
  src/apps/backend/modules/notification/internals/store/account_notification_preferences_repository.py
  src/apps/backend/modules/notification/notification_service.py
  src/apps/backend/modules/notification/sms_service.py
  src/apps/backend/modules/notification/types.py
  tests/modules/account/base_test_account.py
  tests/modules/account/test_account_api.py
  tests/modules/account/test_notification_preferences_api.py
  tests/modules/account/test_notification_preferences_service.py
  tests/modules/authentication/test_access_token_api.py
  tests/modules/authentication/test_access_token_service.py
  tests/modules/authentication/test_otp_whitelist_api.py
  tests/modules/authentication/test_password_reset_token_api.py
Labels: boilerplate

#275 docs: add backend architecture doc
  README.md
  docs/backend-architecture.md
Labels: documentation

#276 feat: add account deletion support
  src/apps/backend/modules/account/account_service.py
  src/apps/backend/modules/account/internal/account_reader.py
  src/apps/backend/modules/account/internal/account_writer.py
  src/apps/backend/modules/account/internal/store/account_repository.py
  src/apps/backend/modules/account/rest_api/account_router.py
  src/apps/backend/modules/account/rest_api/account_view.py
  src/apps/backend/modules/account/types.py
  tests/modules/account/test_account_api.py
  tests/modules/account/test_account_service.py
Labels: enhancement

#283 fix: authentication flows failing due to missing notification preferences
  src/apps/backend/modules/account/account_service.py
  src/apps/backend/modules/authentication/authentication_service.py
  src/apps/backend/modules/notification/email_service.py
  src/apps/backend/modules/notification/sms_service.py
  tests/modules/account/test_notification_preferences_api.py
  tests/modules/account/test_notification_preferences_service.py
  tests/modules/authentication/test_access_token_api.py
  tests/modules/authentication/test_otp_whitelist_api.py
  tests/modules/authentication/test_password_reset_token_api.py
Labels: bug
